### ISSUE TITLE
As a logged-in supplier, I can edit my listings

### ISSUE THREAD

**Issue by laurawhalin** [larsonkonr/The_Pivot#12]
As a logged in supplier I visit my listings page
    When I click on the link of a listing
    I am redirected to the edit listing page
    I edit my listing, including title, description, categories, quantity available, unit size, current location, shippable       indicator and unit weight. 
    click the 'update' button
    I am redirected to my listing page where I see my updated listing

**Comment by scottalexandra** [comment]
duplicate to 27
